service: mail-service
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs14.x

functions:
   sendEmail:
    handler: handler.sendEmail
    events:
      - sqs: 
          arn: ${env:MAIL_QUEUE_ARN}
          batchSize: 1